#!/bin/bash

function check() {
    info=`git st|grep "nothing to commit"`
    if [ "$info" = "" ];then
        echo "请先提交修改后在发布"
        exit
    fi
}

function publish() {
    pushd website
    npm run build
    if [ $? -ne 0 ]; then
        exit
    fi
    mv build ../../.__build
    mv node_modules ../../.__node_modules
    popd
    # 发布
    info=`git br|grep "gh-pages"`
    if [ "$info" = "" ];then
        git copage
    else
        git co gh-pages
        git plpage
    fi
    git lg -5
    if [ -z "$1" ];then
        v=`git lg -1|sed 's/.*发布//'|sed 's/版本.*//'|sed 's/\.//g'`
    else
        v=`echo $1|sed 's/.*发布//'|sed 's/版本.*//'|sed 's/\.//g'`
    fi
    t=`echo $v|grep '^\d\{3\}$'`
    if [ "$t" = "" ];then
        v="99"
        git co -b gh-pages
    fi
    let v=v+1
    v="发布${v:0:1}.${v:1:1}.${v:2:1}版本"
    echo ""
    echo $v
    rm -fr *
    mv ../.__build/fsjz/* .
    git add .
    git ci "$v"
    git pupage
    git co master
    mv ../.__node_modules website/node_modules
    rm -fr ../.__build
}

check
publish "$1"
